### ISSUE TITLE
Poor subscription form aesthetics

### ISSUE THREAD

**Issue by LemonPi** [zhuowei/worthdoingbadly.com#1]
![image](https://user-images.githubusercontent.com/5508542/44045755-8b1042c4-9ef7-11e8-8ac3-b85636046980.png)
Is the lack of spacing between the subscription form and the header intentional for fitting the theme of the website? IMO it looks better with a margin-top of 10px:

![image](https://user-images.githubusercontent.com/5508542/44045914-051f43f8-9ef8-11e8-884a-b22cc72162e4.png)

**Comment by zhuowei** [comment]
@LemonPi I could justify it as best using the limited space on mobile devices, but the real reason is that I'm terrible at CSS.

I'll try your suggestion - thanks!

**Comment by zhuowei** [comment]
Thanks - updated with a 4px top/bottom margin.
<img width="759" alt="nowits4px" src="https://user-images.githubusercontent.com/704768/44245559-3c6a2600-a1a7-11e8-84da-9ed55476247d.png">
